CREATE DATABASE APOLLO_HOSPITAL12;
USE APOLLO_HOSPITAL12;

CREATE TABLE PATIENTS (
    PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    GENDER ENUM('M', 'F', 'O'),
    AGE INT,
    PHONE VARCHAR(15),
    ADDRESS VARCHAR(200)
);


CREATE TABLE DOCTORS(
DOCTOR_ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(100)NOT NULL,
SPECIALIZATION VARCHAR(100),
PHONE VARCHAR(15));



CREATE TABLE APPOINTMENTS(
APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID INT,
DOCTOR_ID INT,
APPOINTMENT_DATE DATE,
STATUS ENUM('SCHEDULED','COMPLETED','CANCELLED') DEFAULT 'SCHEDULED',
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID));



CREATE TABLE BILLING(
BILL_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID INT,
AMOUNT DECIMAL(10,2),
BILL_DATE DATE DEFAULT (CURRENT_DATE),
STATUS ENUM ('PAID','UNPAID') DEFAULT'UNPAID',
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID));

CREATE TABLE PRESCRIPTIONS(
PRESCRIPTION_ID INT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID INT,
DOCTOR_ID INT,
MEDICINE VARCHAR(200),
DOSAGE  VARCHAR(100),
PRESCRIPTION_DATE DATE DEFAULT(current_date),
FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(PATIENT_ID),
FOREIGN KEY (DOCTOR_ID) REFERENCES DOCTORS(DOCTOR_ID));
 
 SHOW TABLES;

INSERT INTO DOCTORS
(NAME,SPECIALIZATION ,PHONE)
VALUES
('DR.RAMESH GUPTA','CARDIOLOGIST','9876543210'),
('DR.NEHA SHARMA','DERMATALOGIST','9876501234'),
('DR.ARJUN MEHTA','NEUROLOGIST','9123456780'),
('DR.KAVITA IYER','PERIATRICIAN','9988776655'),
('DR.RAJESH PATEL','ORTHOPEDIC','9812345678');




INSERT INTO PATIENTS
(NAME,GENDER,AGE,PHONE,ADDRESS)
VALUES
('AMIT KUAMR','M',34,'9871112233','DELHI'),
('SNEHA VERMA','F',28,'9872223344','MUMBAI'),
('RAHUL SINGH','M',45,'9873334455','KOLKATA'),
('PRIYA NAIR','F',52,'9874445566','CHENNAI'),
('VIKRAM DESAI','M',39,'9875556677','AHMEDABAD'),
('ANJALI GUPTA','F',23,'9876667788','LUCKNOW'),
('SURESH REDDY','M',60,'9877778899','HYDERABAD'),
('MEENA JOSHI','F',30,'9878889900','PUNE'),
('RAVI SHANKAR','M',48,'9879990011','BENGALURU'),
('KIRAN BEDI','F',36,'9870001122','DELHI'),
('RAJESH KUMAR','M',41,'9871112234','JAIPUR'),
('POOJA SHARMA','F',29,'9872223345','PATNA'),
('ANKIT VERMA','M',33,'9873334456','BHOPAL'),
('RITIKA SINGH','F',25,'9874445567','INDORE'),
('MANSIH GUPTA','M',38,'9875556678','KANPUR'),
('NEHA REDDY','F',27,'9876667789','VIJAYAWADA'),
('SANDEEP MEHTA','M',50,'9877778890','SURAT'),
('KAVITA NAIR','F',31,'9878889901','TRIVANDRUM'),
('ARJUN PATEL','M',46,'9879990012','RAJKOT'),
('DIVYA JOSHI','F',34,'9870001123','AHMEDABAD'),
('VIKRAM SHARMA','M',42,'9871112235','LUCKNOW'),
('SONAL GUPTA','F',28,'9872223346','PATIALA'),
('ROHIT KUAMR','M',37,'9873334457','JAIPUR'),
('PRIYA REDDY','F',26,'9874445568','HYDERABAD'),
('AAKASH VERMA','M',44,'9875556679','BHOPAL'),
('MEGHA SINGH','F',32,'9876667790','CHANDIGARH'),
('SAURABH PATEL','M',39,'9877778891','AHMEDABAD'),
('ANANYA SHARMA','F',24,'9878889902','DELHI'),
('RAJAT MEHTA','M',47,'9879990013','SURAT'),
('NISHA GUPTA','F',33,'9870001124','MUMBAI'),
('KARAN REDDY','M',51,'9871112236','VIJAYAWADA'),
('SWATI JOSHI','F',30,'9872223347','PUNE'),
('AMIT MEHRA','M',36,'9873334458','DELHI'),
('SHERYA NAIR','F',29,'9874445569','TRIVANDRUM'),
('DEEPAK SHARMA','M',43,'9875556680','LUCKNOW'),
('RITU VERMA','F',27,'9876667791','PATNA'),
('SANJAY KUMAR','M',40,'9877778892','JAIPUR'),
('PRIYANKA GUPTA','F',25,'9878889903','CHENNAI'),
('VIVEK REDDY','M',35,'9879990014','HYDERABAD'),
('ANJALI SHARMA','F',28,'9870001125','DELHI'),
('RAHUL MEHTA','M',38,'9871112237','SURAT'),
('SNEHA NAIR','F',31,'9872223348','TRIVANDRUM'),
('AMAN PATEL','M',45,'9873334459','RAJKOT'),
('DIVYA GUPTA','F',29,'9874445570','MUMBAI'),
('RAKESH VERMA','M',50,'9875556681','BHOPAL'),
('MEERA JOSHI','F',26,'9876667792','AHMEDABAD'),
('AJAY SINGH','M',39,'9877778893','CHANDIGARH'),
('NEHA SHARMA','F',32,'9878889904','DELHI'),
('SIDDHARTH REDDY','M',41,'9879990015','HYDERABAD'),
('ANITA PATEL','F',30,'9870001126','RAJKOT'),
('ROHAN MEHRA','M',37,'9871112238','MUMBAI'),
('SWATI GUPTA','F',28,'9872223349','PUNE'),
('VIKASH SHARMA','M',44,'9873334460','JAIPUR'),
('KIRAN NAIR','F',25,'9874445571','TRIVANDRUM'),
('MANOJ KUMAR','M',46,'9875556682','LUCKNOW'),
('POOJA VERMA','F',27,'9876667793','PATNA'),
('RAMESH REDDY','M',49,'9877778894','HYDERABAD'),
('NIDHI JOSHI','F',33,'9878889905','DELHI'),
('ANKIT PATEL','M',36,'9879990016','RAJKOT'),
('SWETA SHARMA','F',29,'9870001127','CHENNAI'),
('VIKRAM MEHTA','M',42,'9871112239','SURAT'),
('NEHA GUPTA','F',31,'9872223350','MUMBAI'),
('RAJAT REDDY','M',38,'9873334461','HYDERABAD'),
('PRIYA JOSHI','F',26,'9874445572','PUNE'),
('SNAJAY PATEL','M',45,'9875556683','RAJKOT'),
('ANANYA SHARMA','F',28,'9876667794','DELHI'),
('AMIT VERMA','M',40,'9877778895','BHOPAL'),
('RITIKA GUPTA','F',25,'9878889906','AHMEDABAD'),
('ROHIT REDDY','M',37,'9879990017','HYDERABAD'),
('MEENA JOSHI','F',30,'9870001128','PUNE'),
('VIVEK PATEL','M',43,'9871112240','RAJKOT'),
('SWATI SHARMA','F',29,'9872223351','CHENNAI'),
('DEEPAK GUPTA','M',39,'9873334462','MUMBAI'),
('ANJALI VERMA','F',32,'9874445573','DELHI'),
('RAKESH MEHTA','M',41,'9875556684','SURAT'),
('NISHA REDDY','F',27,'9876667795','HYDERABAD'),
('AJAY SHARMA','M',36,'9877778896','LUCKNOW'),
('KAVITA JOSHI','F',30,'9878889907','PUNE'),
('SAURABH PATEL','M',44,'9879990018','RAJKOT'),
('PRIYA GUPTA','F',28,'9870001129','MUMBAI'),
('ROHIT VERMA','M',38,'9871112241','BHOPAL'),
('MEGHA SHARMA','F',26,'9872223352','DELHI');

-- BOOK APPOINTMENT

INSERT INTO APPOINTMENTS(patient_id,doctor_id,appointment_date)
VALUES(1,2,'2025-10-05');

-- ASSIGN DOCTORS & PRESCRIPTION

INSERT INTO PRESCRIPTIONS(PATIENT_ID,DOCTOR_ID,MEDICINE,DOSAGE)
VALUES(1,2,'PARACETAMOL 500MG','1 TABLET TWICE DAILY');

-- GENERATE BILL

INSERT INTO BILLING(PATIENT_ID,AMOUNT,STATUS)
VALUES(1,500.00,'UNPAID');

SELECT * FROM PATIENTS;

-- LIST ALL PATIENTS WITH THEIR PHONE NUMBERS

SELECT 
    NAME, PHONE
FROM
    PATIENTS;
    
 -- COUNT THE TOTAL NUMBER OF PATIENTS
 
 SELECT 
    COUNT(*) AS TOTAL_PATIENTS
FROM
    PATIENTS;

-- SHOW ALL DOCTORS SPECIALIZING IN 'CARDIOLOGIST'

SELECT 
    NAME, PHONE
FROM
    DOCTORS
WHERE
    SPECIALIZATION = 'CARDIOLOGIST';
 
 INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE,STATUS)
 VALUES(1,1,CURDATE(),'SCHEDULED'),
 (5,3,CURDATE(),'SCHEDULED'),
 (10,2,CURDATE(),'SCHEDULED');
 
 -- BOOK APPOINTMENT
 
 INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE)
 VALUES(4,2,CURDATE());
 
 
 -- FIND ALL APPOINTMENTS SCHEDULED FOR TODAY
 
 SELECT * FROM APPOINTMENTS
 WHERE APPOINTMENT_DATE = CURDATE();
 
 SELECT * FROM APPOINTMENTS;
 
 INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE)
 VALUES
 (5,2,CURDATE());
 
 SELECT * FROM APPOINTMENTS;
 
 SELECT * FROM APPOINTMENTS
 WHERE APPOINTMENT_DATE = CURDATE();
 
 -- LIST PATIENTS WHO HAVE APPOINTMENTS WITH 'DR.NEHA SHARMA'
 
 SELECT P.NAME,A.APPOINTMENT_DATE
 FROM APPOINTMENTS A 
 JOIN PATIENTS P ON A.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON A.DOCTOR_ID=D.DOCTOR_ID
 WHERE D.NAME ='DR.NEHA SHARMA';
 
 -- COUNT HOW MANY APPOINTMENTS EACH DOCTOR HAS
 
 SELECT D.NAME,COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENT
 FROM DOCTORS D 
 LEFT JOIN APPOINTMENTS A ON D.DOCTOR_ID=A.DOCTOR_ID
 GROUP BY D.DOCTOR_ID;
 
 -- LIST ALL UNPAID BILL
 
 SELECT B.BILL_ID,P.NAME,B.AMOUNT,B.BILL_DATE
 FROM BILLING B 
 JOIN PATIENTS P ON B.PATIENT_ID=P.PATIENT_ID
 WHERE B.STATUS = 'UNPAID';
 
 -- FIND PATIENTS WHO HAVE NEVER HAD AN APPOINTMENT
 SELECT NAME FROM PATIENTS
 WHERE PATIENT_ID NOT IN (SELECT PATIENT_ID FROM APPOINTMENTS);
 
 
 -- LIST PRESCRIPTION GIVEN BY 'DR.ARJUN MEHTA'
 
 SELECT PR.MEDICINE,PR.DOSAGE,P.NAME AS PATIENT_NAME
 FROM PRESCRIPTIONS PR 
 JOIN PATIENTS P ON PR.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON PR.DOCTOR_ID=D.DOCTOR_ID
 WHERE D.NAME = 'DR.ARJUN MEHTA';
 
 INSERT INTO PRESCRIPTIONS(PATIENT_ID,DOCTOR_ID,MEDICINE,DOSAGE)
 VALUES(1,2,'PARACETAMOL 500MG','1 TABLET TWICE DAILY');
 
 INSERT INTO PRESCRIPTIONS (PATIENT_ID,DOCTOR_ID,MEDICINE,DOSAGE)
 VALUES(1,3,'ASPIRIN 75 MG','TABLET DAILY');
 
  -- LIST PRESCRIPTION GIVEN BY 'DR.ARJUN MEHTA'
 
 SELECT PR.MEDICINE,PR.DOSAGE,P.NAME AS PATIENT_NAME
 FROM PRESCRIPTIONS PR 
 JOIN PATIENTS P ON PR.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON PR.DOCTOR_ID=D.DOCTOR_ID
 WHERE D.NAME = 'DR.ARJUN MEHTA';
 
 -- FIND THE TOTAL BILLING AMOUNT FOR EACH PATIENT
 
 SELECT P.NAME,SUM(B.AMOUNT) AS TOTAL_BILL
 FROM PATIENTS P
 JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID
 GROUP BY P.PATIENT_ID;
 
 -- LIST PATIENTS ABOVE 40 YEAR OF AGE
 
 SELECT NAME,AGE
 FROM PATIENTS
 WHERE AGE > 40;
 
 -- SHOW APPOINTMENTS WITH STATUS 'COMPLETED'
 
 INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE)
 VALUES(1,2,'2025-10-5');
 
 UPDATE APPOINTMENTS
 SET STATUS = 'COMPLETED'
 WHERE APPOINTMENT_ID = 1;
 
 INSERT INTO APPOINTMENTS(PATIENT_ID,DOCTOR_ID,APPOINTMENT_DATE,STATUS)
 VALUES
 (2,1,CURDATE(),'COMPLETED'),
 (3,3,CURDATE(),'CANCELLED'),
 (4,2,CURDATE(),'SCHEDULED');
 
 
 SELECT * FROM APPOINTMENTS;
 
 SELECT A.APPOINTMENT_ID,P.NAME,D.NAME AS DOCTOR_NAME,A.APPOINTMENT_DATE
 FROM APPOINTMENTS A
 JOIN PATIENTS P ON A.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON A.DOCTOR_ID=D.DOCTOR_ID
 WHERE A.STATUS = 'COMPLETED';
 
 -- FIND THE PATIENTS WITH THE HIGHEST SINGLE BILL
 
 SELECT P.NAME,B.AMOUNT
 FROM BILLING B
 JOIN PATIENTS P ON B.PATIENT_ID=P.PATIENT_ID
 ORDER BY B.AMOUNT DESC
 LIMIT 1;
 
 -- COUNT HW MANY MALE AND FEMALE PATIENTS 
 
 SELECT GENDER,COUNT(*) AS TOTAL 
 FROM PATIENTS
 GROUP BY GENDER;
 
 
 -- LIST APPOINTMENTS IN THE NEXT 7 DAYS
 
 SELECT A.APPOINTMENT_ID,P.NAME,D.NAME AS DOCTOR_NAME,A.APPOINTMENT_DATE
 FROM APPOINTMENTS A
 JOIN PATIENTS P ON A.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON A.DOCTOR_ID=D.DOCTOR_ID
 WHERE A.APPOINTMENT_DATE BETWEEN CURDATE() AND DATE_ADD(CURDATE(),INTERVAL 7 DAY) ; 
 
 -- SHOW ALL DOCTORS WHO HAVE NOT BEEN ASSIGNED ANY APPOINTMNENT
 
 SELECT NAME FROM DOCTORS 
 WHERE DOCTOR_ID NOT IN (SELECT DOCTOR_ID FROM APPOINTMENTS);
 
 -- FIND TOTAL NUMBER OF PRESCRIPTIONS ISSUED BY EACH OTHER
 
 SELECT D.NAME,COUNT(PR.PRESCRIPTION_ID) AS TOTAL_PRESCRIPTIONS 
 FROM DOCTORS D 
 LEFT JOIN PRESCRIPTIONS PR ON D.DOCTOR_ID=PR.DOCTOR_ID
 GROUP BY D.DOCTOR_ID;
 
 -- LIST PATIENTS WHO HAVE BILLS ABOVE 1000
 
 INSERT INTO BILLING(PATIENT_ID,AMOUNT,STATUS)
 VALUES
 (2,1500.00,'PAID'),
 (3,2000.00,'UNPAID'),
 (4,1200.00,'PAID');
 
 SELECT P.NAME,B.AMOUNT
 FROM PATIENTS P 
 JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID
 WHERE B.AMOUNT >1000;
 
 -- FIND PATIENTS WHO HAVE MULTIPLE APPOINTMENTS
 
 SELECT P.NAME,COUNT(A.APPOINTMENT_ID) AS APPOINTMENT_COUNT
 FROM PATIENTS P
 JOIN APPOINTMENTS A ON P.PATIENT_ID=A.PATIENT_ID
 GROUP BY P.PATIENT_ID
 HAVING COUNT(A.APPOINTMENT_ID)>1;
 
 -- SHOW ALL APPOINTMENTS WITH PATIENT NAME,DOCTOR NAME,AND STATUS
 
 SELECT A.APPOINTMENT_ID,P.NAME AS PATIENT_NAME,D.NAME AS DOCTOR_NAME,A.STATUS
 FROM APPOINTMENTS A 
 JOIN PATIENTS P ON A.PATIENT_ID=P.PATIENT_ID
 JOIN DOCTORS D ON A.DOCTOR_ID=D.DOCTOR_ID;
 
 -- LIST PATIENTS WHO HAVE BOTH PRESCRIPTIONS AND BILLS
 
 SELECT DISTINCT P.NAME
 FROM PATIENTS P 
 JOIN PRESCRIPTIONS PR ON P.PATIENT_ID=PR.PATIENT_ID
 JOIN BILLING B ON P.PATIENT_ID=B.PATIENT_ID;
 
  -- FIND AVERAGE AGE OF PATIENTS 
  SELECT AVG(AGE) AS AVERAGE_AGE 
  FROM PATIENTS;
  
  -- LIST TOP 5 PATIENTS WITH HIGHEST TOTTAL BILLING
  
  SELECT P.NAME,SUM(B.AMOUNT)AS TOTAL_BILL
  FROM PATIENTS P
  JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID
  GROUP BY P.PATIENT_ID
  ORDER BY TOTAL_BILL DESC
  LIMIT 5;
  
  -- COUNT APPOINTMENT PER STATUS (SCHEDULED/COMPLETED/CANCELLED)
  
  SELECT STATUS,COUNT(*) AS TOTAL
  FROM APPOINTMENTS
  GROUP BY STATUS;
  
  -- SHOW PRESCRIPTIONS FRO PATIENTS WHO ARE ABOVE 50 YEARS OLD 
  INSERT INTO PRESCRIPTIONS(PATIENT_ID,DOCTOR_ID,MEDICINE,DOSAGE)
  VALUES
  (7,1,'ASPRIN 75MG','1 TABLET DAILY'), -- SURESH REDDY
  (4,3,'VITAMIN D','1 CAPSULE DAILY'), -- PRIYA NAIR
  (22,2,'METFORMIN 500MG','1 TABLET TWICE DAILY'); -- KARAN REDDY
  
  
SELECT * FROM PRESCRIPTIONS;

SELECT P.NAME,PR.MEDICINE,PR.DOSAGE
FROM PRESCRIPTIONS PR 
JOIN PATIENTS P ON PR.PATIENT_ID=P.PATIENT_ID 
WHERE P.AGE >50;

 
 
-- TOP DOCTOR WITH MOST APPOINTMENTS

SELECT D.NAME, COUNT(A.APPOINTMENT_ID) AS TOTAL_APPOINTMENTS
FROM DOCTORS D
JOIN APPOINTMENTS A ON D.DOCTOR_ID = A.DOCTOR_ID
GROUP BY D.DOCTOR_ID, D.NAME
ORDER BY TOTAL_APPOINTMENTS DESC
LIMIT 1;

-- DOCTOR WHOSE PATIENTS GENERATED HIGHEST BILLING

SELECT D.NAME, SUM(B.AMOUNT) AS TOTAL_REVENUE
FROM DOCTORS D
JOIN APPOINTMENTS A ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN BILLING B ON A.PATIENT_ID = B.PATIENT_ID
GROUP BY D.DOCTOR_ID, D.NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 1;

-- PATIENT WHO HAVE APPOINTMENT BUT NO PRESCRIPTION

SELECT DISTINCT P.NAME
FROM PATIENTS P
JOIN APPOINTMENTS A ON P.PATIENT_ID = A.PATIENT_ID
LEFT JOIN PRESCRIPTIONS PR ON P.PATIENT_ID=PR.PATIENT_ID
WHERE PR.PRESCRIPTION_ID IS NULL;

-- PATIENTS WHO VISITED SAME DOCTOR MORE THAN ONCE

SELECT P.NAME, D.NAME AS DOCTOR_NAME, COUNT(*) AS VISIT_COUNT
FROM APPOINTMENTS A
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
JOIN DOCTORS D ON A.DOCTOR_ID = D.DOCTOR_ID
GROUP BY P.PATIENT_ID, D.DOCTOR_ID, P.NAME, D.NAME
HAVING COUNT(*) > 1;

-- MOST COMMON MEDICINE PRESCRIBED

SELECT MEDICINE, COUNT(*) AS TOTAL_TIMES
FROM PRESCRIPTIONS
GROUP BY MEDICINE
ORDER BY TOTAL_TIMES DESC
LIMIT 1;

-- AVERAGE BILLING PER PATIENT

SELECT P.NAME, AVG(B.AMOUNT) AS AVG_BILL
FROM PATIENTS P
JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID
GROUP BY P.PATIENT_ID, P.NAME;

-- DOCTOR WHO HAVE TREATED PATIENTS ABOVE 50 YEARS

SELECT DISTINCT D.NAME
FROM DOCTORS D
JOIN APPOINTMENTS A ON D.DOCTOR_ID = A.DOCTOR_ID
JOIN PATIENTS P ON A.PATIENT_ID = P.PATIENT_ID
WHERE P.AGE > 50;

-- PATIENTS WITH HIGHEST TOTAL BILL

SELECT P.NAME, SUM(B.AMOUNT) AS TOTAL_BILL
FROM PATIENTS P
JOIN BILLING B ON P.PATIENT_ID = B.PATIENT_ID
GROUP BY P.PATIENT_ID, P.NAME
ORDER BY TOTAL_BILL DESC
LIMIT 1;

COMMIT;
 
 
 
 
 
 
 
 
